# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af028f629bab523b077f94f316c944d4083e8e65bd5c4502ed14ea59c8a026d66ed151ac0e7b89fafe60f17f73f2389afaba1e87154885b8fe103e67699f2139

test:
  secret_key_base: 12c68fe075a2b901239e9569331df18c84b90429e63e19487ad4ebb7ffbf2d28b9a5090e6f04ce5109c4f2b19e8e879caf41522eed4ddfde5d649a85f811a9ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
